# Generated by Django 5.0.1 on 2024-01-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Confirmpass', models.CharField(max_length=100)),
            ],
        ),
    ]
